version: "3.7"

services:

  nginx:
    image: nginx:1.19.5
    ports:
      - 80:80
    networks:
      - next_project_network
    volumes:
      - /home/utmdans/nginx.conf:/etc/nginx/nginx.conf
      - nextproject_static:/data/static/
      - nextproject_media:/data/media/

  django:
    image: nextproject_django:3
    networks:
      - next_project_network
    volumes:
      - nextproject_static:/home/NEXTPROJECT/staticfiles/
      - nextproject_media:/home/NEXTPROJECT/media/
    secrets:
      - NEXTPROJECT_DJANGO_SECRET_KEY




  mariadb:
    image: mariadb:10.5
    networks:
      - next_project_network
    volumes:
      - nextproject_mariadb:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: password1234
      MARIADB_DATABASE: django
      MARIADB_USER: django
      MARIADB_PASSWORD: password1234

networks:
  next_project_network:

volumes:
  nextproject_static:
  nextproject_media:
  nextproject_mariadb:

secrets:
  NEXTPROJECT_DJANGO_SECRET_KEY:
    external: true