version: "3.7"

services:

  nginx:
    image: nginx:1.19.5
    ports:
      - 80:80
    networks:
      - next_project_network
    volumes:
      - /home/utmdans/nginx.conf:/etc/nginx/nginx.conf
      - nextproject_static:/data/static/
      - nextproject_media:/data/media/

  django:
    image: nextproject_django:5
    networks:
      - next_project_network
    volumes:
      - nextproject_static:/home/NEXTPROJECT/staticfiles/
      - nextproject_media:/home/NEXTPROJECT/media/
    secrets:
      - NEXTPROJECT_DJANGO_SECRET_KEY
      - MARIADB_USER
      - MARIADB_PASSWORD

  mariadb:
    image: mariadb:10.5
    networks:
      - next_project_network
    volumes:
      - nextproject_mariadb:/var/lib/mysql
    secrets:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_USER
      - MARIADB_PASSWORD
    environment:
      MARIADB_DATABASE: django
      MARIADB_USER_FILE: /run/secrets/MARIADB_USER
      MARIADB_PASSWORD_FILE: /run/secrets/MARIADB_PASSWORD
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/MARIADB_ROOT_PASSWORD

networks:
  next_project_network:

volumes:
  nextproject_static:
  nextproject_media:
  nextproject_mariadb:

secrets:
  NEXTPROJECT_DJANGO_SECRET_KEY:
    external: true
  MARIADB_ROOT_PASSWORD:
    external: true
  MARIADB_USER:
    external: true
  MARIADB_PASSWORD:
    external: true